- name: Git personal setup email
  git_config:
    name: user.email
    scope: global
    value: "moritz.schwerer@gmx.de"
  tags:
  - git-personal
- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: "MoritzSchwerer"
  tags:
  - git-personal
