- name: Remove neovim pre build
  shell: rm -rf ~/neovim
  tags:
    - install
    - neovim
- name: Clone Neovim
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "/tmp/neovim"
  tags:
    - install
    - neovim
- name: Build neovim
  shell: "cd /tmp/neovim && make CMAKE_BULID_TYPE=RelWithDebInfo"
  tags:
    - install
    - neovim
- name: Install neovim
  become: true
  shell: "cd /tmp/neovim && make install"
  tags:
    - install
    - neovim

- name: Clone committer
  ansible.builtin.git:
    repo: 'https://github.com/2kabhishek/committer.git'
    dest: "/tmp/committer"
  tags:
    - neovim
    - install

- name: Install committer
  shell: "cd /tmp/committer && cp committer.sh {{ lookup('env', 'HOME') }}/.local/bin/committer"
  tags:
    - neovim
    - install

