- name: Install util packages (tmux, fzf, rg, tree, exa)
  become: true 
  apt:
    name:
      - tmux
      - fzf
      - ripgrep
      - tree
      - exa

  tags: 
    - install 

- name: Dev tools
  become: true
  apt:
    name: 
      - python3-pip
      - cargo
  tags: install
