- name: Install util packages (nvim, tmux, fzf, rg, tree, ranger)
  become: true 
  apt:
    name:
      - neovim
      - tmux
      - fzf
      - ripgrep
      - tree
      - ranger
  tags: 
    - install 
